name: Create Issue on Test Failure

on:
  workflow_run:
    workflows: ["CI"]
    types: 
      - completed

jobs:
  create_issue:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: peter-evans/create-issue@v3
        with:
          title: Test Failure Detected
          body:
            The tests have failed. Please investigate and take necessary actions to fix the issue.
            Workflow: ${{ github.workflow }}
            Run ID: ${{ github.run_id }}
            Repository: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Failed Job: ${{ github.job }}
            Failed Workflow Run: ${{ github.event.workflow_run.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
